<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZRym2rc\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZRym2rc/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZRym2rc.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZRym2rc\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZRym2rc\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ZRym2rc',
    'container.build_id' => 'c056c283',
    'container.build_time' => 1565162734,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZRym2rc');
