<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.IkQ09Xo' shared service.

return $this->privates['.service_locator.IkQ09Xo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\CompteController::compte' => ['privates', '.service_locator.7zWnKy7', 'get_ServiceLocator_7zWnKy7Service.php', true],
    'App\\Controller\\DepotController::compte' => ['privates', '.service_locator.7zWnKy7', 'get_ServiceLocator_7zWnKy7Service.php', true],
    'App\\Controller\\PartenairesController::register' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\SecurityController::register' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\CompteController:compte' => ['privates', '.service_locator.7zWnKy7', 'get_ServiceLocator_7zWnKy7Service.php', true],
    'App\\Controller\\DepotController:compte' => ['privates', '.service_locator.7zWnKy7', 'get_ServiceLocator_7zWnKy7Service.php', true],
    'App\\Controller\\PartenairesController:register' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\SecurityController:register' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
], [
    'App\\Controller\\CompteController::compte' => '?',
    'App\\Controller\\DepotController::compte' => '?',
    'App\\Controller\\PartenairesController::register' => '?',
    'App\\Controller\\SecurityController::register' => '?',
    'App\\Controller\\CompteController:compte' => '?',
    'App\\Controller\\DepotController:compte' => '?',
    'App\\Controller\\PartenairesController:register' => '?',
    'App\\Controller\\SecurityController:register' => '?',
]);
